pets_web:
    resource: "@petsWebBundle/Resources/config/routing.yml"
    prefix:   /

vallbona_web:
    resource: "@VallbonaWebBundle/Resources/config/routing.yml"
    prefix:   /public-web

app:
    resource: '@AppBundle/Controller/'
    type: annotation
