<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZdcwi1j\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZdcwi1j/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZdcwi1j.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZdcwi1j\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZdcwi1j\appProdProjectContainer(array(
    'container.build_hash' => 'Zdcwi1j',
    'container.build_id' => 'a7f1cc4e',
    'container.build_time' => 1519052064,
));
