<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSyz199p\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSyz199p/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSyz199p.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSyz199p\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSyz199p\appProdProjectContainer(array(
    'container.build_hash' => 'Syz199p',
    'container.build_id' => '2d7ca02b',
    'container.build_time' => 1519743816,
));
