pets_web_homepage:
    path:     /
    defaults: { _controller: petsWebBundle:Default:index }
pets_web_form:
    path:     /formUsuaris
    defaults: { _controller: petsWebBundle:Forms:create }
pets_web_form:
    path:     /formTasques
    defaults: { _controller: petsWebBundle:Forms:create }
pets_web_form:
    path:     /formSubtasques
    defaults: { _controller: petsWebBundle:Forms:create }
