<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVrakxjs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVrakxjs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVrakxjs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVrakxjs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVrakxjs\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vrakxjs',
    'container.build_id' => 'd7dc01ad',
    'container.build_time' => 1519313589,
));
