vallbona_web_homepage:
    path:     /home
    defaults: { _controller: VallbonaWebBundle:Default:index }

vallbona_web_articles:
    path:     /articles
    defaults: { _controller: VallbonaWebBundle:Default:articles }

vallbona_web_articlesDetall:
    path:     /articles/{id}
    defaults: { _controller: VallbonaWebBundle:Default:articlesDetall }