<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVtfcyso\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVtfcyso/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVtfcyso.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVtfcyso\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVtfcyso\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vtfcyso',
    'container.build_id' => '0a514933',
    'container.build_time' => 1519313617,
));
