<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDeag5dx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDeag5dx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDeag5dx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDeag5dx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDeag5dx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Deag5dx',
    'container.build_id' => '1c834f4b',
    'container.build_time' => 1521474942,
));
