<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMzjqnup\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMzjqnup/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMzjqnup.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMzjqnup\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMzjqnup\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mzjqnup',
    'container.build_id' => '0af444cb',
    'container.build_time' => 1519742097,
));
