<?php

namespace Proxies\__CG__\pets\WebBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tasques extends \pets\WebBundle\Entity\Tasques implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'idTasca', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'titol', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'descripcio', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'dataInici', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'dataFinal', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'estat', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'prioritat', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'departament'];
        }

        return ['__isInitialized__', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'idTasca', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'titol', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'descripcio', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'dataInici', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'dataFinal', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'estat', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'prioritat', '' . "\0" . 'pets\\WebBundle\\Entity\\Tasques' . "\0" . 'departament'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tasques $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdTasca()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdTasca();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTasca', []);

        return parent::getIdTasca();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitol($titol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitol', [$titol]);

        return parent::setTitol($titol);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitol', []);

        return parent::getTitol();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcio($descripcio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcio', [$descripcio]);

        return parent::setDescripcio($descripcio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcio', []);

        return parent::getDescripcio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInici($dataInici)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInici', [$dataInici]);

        return parent::setDataInici($dataInici);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInici()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInici', []);

        return parent::getDataInici();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFinal($dataFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFinal', [$dataFinal]);

        return parent::setDataFinal($dataFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFinal', []);

        return parent::getDataFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstat($estat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstat', [$estat]);

        return parent::setEstat($estat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstat', []);

        return parent::getEstat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrioritat($prioritat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrioritat', [$prioritat]);

        return parent::setPrioritat($prioritat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrioritat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrioritat', []);

        return parent::getPrioritat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartament($departament)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartament', [$departament]);

        return parent::setDepartament($departament);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartament()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartament', []);

        return parent::getDepartament();
    }

}
